name: Publish to NPM
on:
  pull_request:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to NPM
        if: github.event.pull_request.merged == true
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: yarn
      - run: sh ./prepare-publish.sh
      - run: yarn beachball publish -y
      - run: yarn build
      - run: sh ./publish.sh
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
