name: Release Management
on:
  pull_request:
    branches:
      - master

jobs:
  check-version-bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Danger JS Action
        uses: danger/danger-js@9.2.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
